version: '3'
services:
  mongo-srv:
    container_name: mongo-srv
    image: mongo:latest
    restart: always
    networks:
      - net
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  postgres-srv:
    image: postgres:11.1
    container_name: postgres-srv
    networks:
      - net
    ports:
      - 5433:5432
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data:rw
    environment:
      LC_ALL: 'C.UTF-8'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_DB: keycloak
      PGDATA: /var/lib/postgresql/data
    restart: unless-stopped
  keycloak-srv:
    image: jboss/keycloak:12.0.0
    container_name: keycloak-srv
    networks:
      - net
    ports:
      - "7070:8080"
    expose:
      - "7070"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-srv
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: keycloak
      DB_SCHEMA: public
    depends_on:
      - postgres-srv
    restart: unless-stopped
#  music-srv:
#    build: ./
#    container_name: music-srv
#    networks:
#      - net
#    ports:
#      - "8000:8000"
#    expose:
#      - "8000"
#    restart: unless-stopped
#    environment:
#      - "SERVICE_NAME=music-srv"
#      - "PORT=8000"
#      - "KEYCLOAK_URI=http://keycloak-srv:8080/auth"
#      - "KEYCLOAK_CLIENT_SECRET=f9e363b1-3599-4ca7-ba44-2b3d5d5c57dc"
#      - "EUREKA_ENABLED=false"
networks:
  net:
    driver: "bridge"
