version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sinkerflow
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
networks:
  net:
    driver: "bridge"
