spring:
  application:
    name: music
keycloak:
  realm: develop
  auth-server-url: ${KEYCLOAK_URI:http://keycloak-service:8080/auth}
  ssl-required: external
  resource: music-service
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
  use-resource-role-mappings: true
  bearer-only: true
  principal-attribute: preferred_username


--- # cloud
server:
  port: ${PORT:8080}
spring:
  config:
    activate:
      on-profile: cloud
  data:
    mongodb:
      host: mongo-srv
      port: 27017
      database: sinkerflow

#STACKTRACE_MODE_ENABLED: ${STACKTRACE_MODE_ENABLED:false}

--- # develop
server:
  port: ${PORT:8080}
spring:
  profiles:
    active: develop
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sinkerflow

#STACKTRACE_MODE_ENABLED: ${STACKTRACE_MODE_ENABLED:true}
