name: Pipline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: JDK 11 configuration
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: MongoDB 4.2 configuration
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2

      - name: Maven build
        run: chmod +x mvnw & ./mvnw clean package

      - name: Set up Docker Buildx
        id: sinkerflow-music-api
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/sinkerflow/sinkerflow-music-api:1.0
          push: ${{ github.ref == 'refs/heads/main' }}
