name: Pipline
on:
  push:
    branches:
      - main
      - ISSUE-008
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: JDK 11 configuration
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: MongoDB 4.2 configuration
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2

      - name: Maven build
        run: chmod 777 mvnw & ./mvnw clean package

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push DockerHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: mishachernsyhev14/sinkerflow:2.0
          push: true
          
      - name: Upload Files
        uses: siva1024/scp-deployer@latest
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/"    
      - name: Deploy with docker-compose
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.REMOTE_HOST }}
           username: ${{ secrets.REMOTE_USER }}
           key: ${{ secrets.SERVER_SSH_KEY }}
           port: 22
           script: sudo docker-compose up -d
