name: Pipline
on:
  push:
    branches:
      - main
      - ISSUE-008
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: JDK 11 configuration
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: MongoDB 4.2 configuration
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2

      - name: Maven build
        run: chmod 777 mvnw & ./mvnw clean package

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: mishachernsyhev14/sinkerflow:2.0
          push: true
          
      - name: Start Deployment
        uses: TapTap21/docker-remote-deployment-action@v1.0
        with:
          remote_docker_host: ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 
          ssh_private_key: ${{ secrets.SERVER_SSH_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          stack_file_name: docker-compose.yml

#       - name: push to kuber
#         uses: Consensys/kubernetes-action@master
#         env:
#           KUBE_CONFIG_DATA: ${{secrets.KUBE_CONFIG_DATA}}
#         with:
#           args: --insecure-skip-tls-verify apply -f sinkerflow-music-api.yaml
