name: build
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: JDK 11 configuration
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: MongoDB 4.2 configuration
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2

      - name: Maven build
        run: ./mvnw clean package
